name: Release 🔖

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    packages: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@main

            - name: Setup NodeJS
              uses: actions/setup-node@main
              with:
                  node-version: 20

            - name: Install
              run: npm ci

            - name: Test 🧪
              run: npm run test

    release-note:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@main

            - name: Create Release Note 🔖
              run: |
                  VERSION=v$(node -p "require('./package.json').version")
                  git config --global user.email "github-actions@github.com"
                  git config --global user.name "GitHub Actions"
                  if git rev-parse "v$VERSION" >/dev/null 2>&1; then
                    echo "Tag v$VERSION already exist."
                    exit 1
                  fi
                  git tag -a "$VERSION" -m "release $VERSION"
                  git push origin "$VERSION"
                  gh release create "$VERSION" -t "$VERSION" --target "${{ github.sha }}" --generate-notes
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash

    publish:
        runs-on: ubuntu-latest
        needs: release-note

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@main

            - name: Setup NodeJS
              uses: actions/setup-node@main
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: PrePublish
              run: npm ci && npm run build

            - name: Publish
              run: npm publish ./package --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
